name: Release

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - run: docker build . -t dockerkr12/nest-app
    - run: echo "${{secrets.DOCKERHUB_USERNAME}}" | docker login -u ${{secrets.DOCKERHUB_USERNAME}}
    - run: docker push dockerkr12/nest-app